name: Build and Test

on:
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: ./ci

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout out code
        uses: actions/checkout@v4
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: "19"
          distribution: "temurin"
          cache: maven
      - name: Build and Test Java Spring Boot Project
        run: mvn clean package
