name: Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.HOST }}
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
      - name: Updating ciserver service to run latest
        run: ssh -t ${{ secrets.USER}}@${{ secrets.HOST}} 'cd ~/DD2480_CI/ci && git pull && mvn clean package && sudo systemctl enable ciserver && sudo systemctl restart ciserver'
